
- name: Build sorm_logs_admin docker image
  docker_image:
    build:
      path: "{{ app_source_code_path }}"
      pull: no
    name: "{{ sorm_logs_admin_docker_image }}"
    tag: "{{ tag }}"
    push: no
    source: build
    state: present
    force_source: true  # Use with state present to build, load or pull an image (depending on
    # the value of the source option) when the image already exists.