- name: "Deploy sorm_logs project"
  hosts: localhost
  vars:
    project_dir: /sorm_logs/
    mysql_expose_port: 3336
    clickhouse_expose_port: 8133
    app_expose_port: 80
    sorm_logs_backup_expose_port: 9070
  roles:
#    - role: docker-engine
#      become: yes
    - environment
    - mariadb
    - clickhouse
    - admin
    - sorm_logs_backup
