- name: "Deploy sorm_logs for development"
  hosts: develop
  vars:
    dev: yes
    project_dir: /home/andrey/sorm_logs_dev
    mysql_expose_port: 3336
    clickhouse_expose_port: 8133
    admin_expose_port: 9001
    sorm_logs_backup_expose_port: 9002
  roles:
#    - role: docker-engine
#      become: yes
#    - environment
#    - mariadb
#    - clickhouse
    - admin
    - sorm_logs_backup

