- name: "Build and push to registry sorm_logs app image"
  hosts: 127.0.0.1
  connection: local
  tasks:
    - name: Log into DockerHub
      docker_login:
        username: "{{ docker_registry_username }}"
        password: "{{ docker_registry_password }}"

    - name: Build an image and push it to a private repo
      docker_image:
        build:
          path: ../
        name: "{{ docker_registry_username }}/s-logs"
        tag: latest
        push: yes
        state: present
        source: build
        force_source: true  # Use with state present to build, load or pull an image (depending on
        # the value of the source option) when the image already exists.