- name: "Deploy sorm_logs app"
  hosts: 127.0.0.1
  connection: local
  tasks:
    - name: Build an image and push it to a private repo
      docker_image:
        build:
          path: ../
        name: "{{ docker_registry_username }}/s-logs"
        tag: latest
        push: no
        state: present
        source: build
        force_source: true  # Use with state present to build, load or pull an image (depending on
        # the value of the source option) when the image already exists.