- name: sorm_logs_backup settings directory
  file:
    path: "{{ project_dir }}/etc/sorm_logs_backup"
    state: directory

- name: sorm_logs_backup settings file
  template:
    src: sorm_logs_backup_config.yml
    dest: "{{ project_dir }}/etc/sorm_logs_backup/config.yml"
    mode: 0644

- name: backups directory
  file:
    path: "{{ project_dir }}/var/backups"
    state: directory

- include: sorm_logs_backup_build_docker_image.yml tag=dev


- name: Run sorm_logs_backup_bundled docker container
  docker_container:
    name: "{{ sorm_logs_backup_docker_container_name }}"
    image: "{{ sorm_logs_backup_docker_image }}:dev"
    state: started
    restart_policy: 'no'
    recreate: yes
    ports:
      - "{{ sorm_logs_backup_expose_port }}:80"
    networks_cli_compatible: yes
    networks:
      - name: sorm_logs_network
    volumes:
      - "{{ project_dir }}/var/clickhouse:{{ clickhouse_data_path }}"
      - "{{ project_dir }}/var/backups:/backups"
      - "{{ project_dir }}/etc/sorm_logs_backup/config.yml/:{{ sorm_logs_backup_config_path }}"
      - "{{ sorm_logs_backup_source_code_path }}:/code"
    env:
      SORM_LOGS_BACKUP_CONFIG: '{{ sorm_logs_backup_config_path }}'

