---

- name: mariadb var directory
  file:
    path: "{{ project_dir }}/var/mariadb"
    state: directory

- name: mariadb etc directory
  file:
    path: "{{ project_dir }}/etc/mariadb"
    state: directory

- name: mariadb config
  template:
    src: mysql.cnf
    dest: "{{ project_dir }}/etc/mariadb/mysql.cnf"
    mode: 0644

- name: start mariadb container
  docker_container:
    name: "{{ sorm_logs_mariadb_docker_container_name }}"
    image: mariadb:10.4
    state: started
    restart_policy: always
    ports:
      - "{{ mysql_expose_port }}:3306"
    networks_cli_compatible: yes
    networks:
      - name: sorm_logs_network
    env:
      MYSQL_ROOT_PASSWORD: "{{ mysql_root_password }}"
      MYSQL_DATABASE: sorm_logs
      MYSQL_USER: "{{ mysql_user }}"
      MYSQL_PASSWORD: "{{ mysql_password }}"
    volumes:
      - "{{ project_dir }}/var/mariadb:/var/lib/mysql"
      - "{{ project_dir }}/etc/mariadb:/etc/mysql/conf.d"

