- name: django settings directory
  file:
    path: "{{ project_dir }}/etc/admin"
    state: directory

- name: django settings
  template:
    src: django_settings.py
    dest: "{{ project_dir }}/etc/admin/django_settings.py"
    mode: 0644

- include: sorm_logs_admin_build_docker_image.yml tag=dev

- name: Make sorm_logs admin docker container for shell access
  docker_container:
    name: "{{ sorm_logs_admin_docker_container_name }}_shell"
    image: "{{ sorm_logs_admin_docker_image }}:dev"
    state: started
    restart_policy: 'no'
    recreate: yes
    ports:
      - "{{ admin_expose_port }}:80"
    networks_cli_compatible: yes
    networks:
      - name: sorm_logs_network
    command: ["tail", "-f", "/dev/null"]
    volumes:
      - "{{ admin_source_code_path }}:/code"
      - "{{ project_dir }}/etc/admin:/code/sorm_logs_custom_settings"
    env:
      DJANGO_SETTINGS_MODULE: sorm_logs_custom_settings.django_settings

